version: 2
updates:
  - package-ecosystem: cargo
    directory: "app"
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: "crates/contained"
    schedule:
      interval: daily