version: "3.9"
services:
  cache:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - /data/redis:/usr/local/etc/redis
  
  database:
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - /data/postgres:/var/lib/postgresql/data





volumes:
  config:
  data:
