version: "4.0"
services:
  cache:
    container_name: cache
    image: redis
    ports:
      - "6379:6379"
    restart: always

  database:
    container_name: database
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - /data/database:/var/lib/postgresql/data

volumes:
  data: