[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://gitlab.com/FL03)"]
categories = []
description = "Chaos is a complete cloud storage solution specializing in decentralized service providers"
edition = "2021"
homepage = "https://gitlab.com/FL03/template-restful-rust/-/wikis/home"
keywords = ["application", "restful"]
license = "MIT"
name = "chaos-api"
readme = "https://gitlab.com/FL03/template-restful-rust/#README"
repository = "https://gitlab.com/template-restful-rust"
version = "0.1.0"

[build-dependencies]

[dependencies]
anyhow = "1.0.64"
axum = { features = ["headers"], version = "0.5.15" }
axum-auth = "0.3.0"
axum-macros = "0.2.3"
axum-sessions = "0.3.1"
axum_sessions_auth = "4.0.0"
bcrypt = "0.13.0"
futures = "0.3.24"
glob = "0.3.0"
http = "0.2.8"
hyper = { features = ["full"], version = "0.14.20" }
jsonwebkey = "0.3.5"
openidconnect = "2.3.2"
redis = "0.21.6"
reqwest = "0.11.11"
scsys = { features = ["full"], git = "https://github.com/scattered-systems/scsys" }
sea-orm = { features = ["sqlx-postgres"], version = "0.9.2" }
serde = { features = ["derive"], version = "1.0.144" }
serde_json = "1.0.85"
tera = "1.17.0"
tokio = { features = ["full"], version = "1.20.1" }
tower = "0.4.13"
tower-cookies = "0.7.0"
tower-http = { features = ["full"], version = "0.3.4" }
tracing = "0.1.35"
tracing-subscriber = { features = ["env-filter"], version = "0.3.14" }

[dev-dependencies]

