[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://gitlab.com)", "Scattered-Systems (https://github.com/scattered-systems)"]
categories = []
description = "Chaos is next-generation cloud storage solution designed to support a myriad of different workflows"
edition = "2021"
homepage = "https://scattered-systems.github.io/chaos/"
keywords = []
license = "MIT"
name = "chaos-cli"  # Move to chaotic, name is already reserved
readme = "https://github.com/scattered-systems/chaos/#README.md"
repository = "https://github.com/scattered-systems/chaos"
version = "0.1.0"

[dependencies]
clap = { features = ["derive"], version = "3.2.20" }
futures = "0.3.23"
glob = "0.3.0"
rand = "0.8.5"
redis = "0.21.6"
reqwest = "0.11.11"
serde = { features = ["derive"], version = "1.0.144" }
serde_json = "1.0.85"
strum = { features = ["derive"], version = "0.24.1" }
tokio = { features = ["full"], version = "1.21.0" }

[dependencies.scsys]
features = ["full"]
version = "0.1.15"

[dependencies.chaos-sdk]
features = ["full"]
path = "../../lib/sdk"