[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://gitlab.com/FL03)", "Scattered-Systems (https://github.com/scattered-systems)"]
categories = []
description = "Chaos is a complete cloud storage solution specializing in decentralized service providers"
edition = "2021"
homepage = "https://github.com/Scattered-Systems/chaos/wiki"
keywords = ["application", "restful"]
license = "MIT"
name = "chaos"
repository = "https://github.com/Scattered-Systems/chaos"
version = "0.1.0"

[build-dependencies]

[dependencies]
bcrypt = "0.13.0"
futures = "0.3.24"
http = "0.2.8"
rust-s3 = "0.32.3"
scsys = { features = ["full"], version = "0.1.17"}
serde = { default-features = false, features = ["derive"], version = "1.0.145" }
serde_json = "1.0.85"
strum = { features = ["derive"], version = "0.24.1" }
tarpc = { features = ["tokio1"], version = "0.31.0" }
tokio = { features = ["full"], version = "1.21.2" }
tower = "0.4.13"
tower-cookies = "0.7.0"
tower-http = { features = ["full"], version = "0.3.4" }
tracing = "0.1.36"
tracing-subscriber = { features = ["env-filter"], version = "0.3.15" }

[dependencies.chaos-sdk]
features = ["full"]
path = "../../lib/sdk"

[dev-dependencies]

