version: "3.9"
services:
  application:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: chaos
    depends_on:
      - cache
      - database
    ports:
      - "9099:9099"
    restart: always
    volumes:
      - /data/app:/data

  cache:
    container_name: cache
    image: redis
    ports:
      - "6379:6379"
    restart: always

  database:
    container_name: database
    environment:
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /data/database:/var/lib/postgresql/data

volumes:
  data: