name: Rust

on:
  push:
    branches: [ "*", "!dev" ]
  pull_request:
    branches: [ "*", "!dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  contained:
    env:
      CARGO_PKG_NAME: contained
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Test
        run: cargo test -p $CARGO_PKG_NAME -v --color $CARGO_TERM_COLOR
      - name: Build and Push
        run: cargo publish -p $CARGO_PKG_NAME -v --color $CARGO_TERM_COLOR
  disarray:
    env:
      CARGO_PKG_NAME: disarray
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Test
        run: cargo test -p $CARGO_PKG_NAME -v --color $CARGO_TERM_COLOR
      - name: Build and Push
        run: cargo publish -p $CARGO_PKG_NAME -v --color $CARGO_TERM_COLOR