name: Rust

on:
  push:
    branches: [ "master" ]
    tags: [ "latest" ]
  pull_request:
    branches: [ "master" ]
    tags: [ "latest" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: cargo test --workspace
  crate:
    env:
      CARGO_PKG_NAME: chaos-sdk
    needs: [ "login", "test" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Push
        run: cargo publish --package $CARGO_PKG_NAME --all-features --token ${{ secrets.CARGO_REGISTRY_TOKEN }}