name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_PKG_VERSION: 0.1.4
  CARGO_TERM_COLOR: always

jobs:
  disarray:
    env:
      CARGO_PKG_NAME: disarray
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Test
        run: cargo test -p $CARGO_PKG_NAME -v --color $CARGO_TERM_COLOR --all-features
      - name: Build and Push
        run: cargo publish -p $CARGO_PKG_NAME -v --color $CARGO_TERM_COLOR --all-features
  disarray-core:
    env:
      CARGO_PKG_NAME: disarray-core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Test
        run: cargo test -p $CARGO_PKG_NAME -v --color $CARGO_TERM_COLOR --all-features
      - name: Build and Push
        run: cargo publish -p $CARGO_PKG_NAME -v --color $CARGO_TERM_COLOR --all-features