name: Rust

on:
  push:
    branches: [ "*", "!dev" ]
  pull_request:
    branches: [ "*", "!dev" ]

env:
  PACKAGE_NAME: contained
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Test
        run: cargo test --package $PACKAGE_NAME --verbose
      - name: Build and Push
        run: cargo publish --package $PACKAGE_NAME --verbose --color