name: Rust

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRY_TOKEN: ${CARGO_REGISTRY_TOKEN}

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login
      run: cargo login ${CARGO_REGISTRY_TOKEN}
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose --workspace
    - name: Test
      run: cargo test --all-features --release --verbose
  publish:
    needs: [ build, login ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Publish
      run: |
        cargo publish --all-features --jobs 1 --token $CARGO_REGISTRY_TOKEN --verbose -p chaos-sdk